### PR TITLE
🎉 New method: pickAll (102 B)

### PR DESCRIPTION
**Pull request by Beraliv**

### CODE REVIEW

**Comment by Beraliv** [comment]
Investigated a bit

using `reduce`

image

using `for(;;)`
run `10` times

image

**Comment by Beraliv** [comment]
PR will contain refactoring of `*.performance.js`

**Comment by Kelin2025** [comment]
@beraliv Can I merge?

**Comment by Beraliv** [comment]
See changes
@Kelin2025 @BabkinAleksandr

**Pull request merged**
